---
title: "BioHub: SARS-CoV-2"
author: "Nicole Liechti"
date: "v1.0"
output: 
  flexdashboard::flex_dashboard:
  orientation: rows
params:
     input: ""
     wd: ""
---

# Sidebar {.sidebar}
```{r, echo=F, warning=F}
path=paste(params$wd, "/Consensus/M3.fa", sep ="")
```


* [Download Sequences](`r paste(params$wd, "/Consensus/allSequences.fasta", sep ="")`)

* [View Nextclade](https://clades.nextstrain.org/){target="_blank"}


# Overview


```{r, echo=F, warning=F}

library(knitr)
library(DT)

setwd(params$wd)

file <- params$input

d <- read.csv(file, sep = ",", header=T)
colnames(d) <- c("Name","PangoLinage", "WHOLinage", "Mean_Coverage", "Coverage_minDP10", "%_Coverage_minDP10", "MappedReads", "TotalReads", "%N_Consensus", "Vadr_QC")
 
 DT::datatable(d, rownames = F, class = "cell-border stripe",
              extensions = c("Buttons", "Select", "SearchPanes", "FixedColumns"),
              selection = "none",
              filter = "top",
              callback = JS("$.fn.dataTable.ext.errMode = 'none';"),
              options = list(
                #autoWidth = T,
                dom = "Bfrt",
                pageLength = 1000,
                searchHighlight = T,
                buttons = c("csv", "excel", "pdf"),
                #scrollX = "400px",
                scrollY = "600px",
                #fillContainer = TRUE,
                scroller = T,
                #pageResize = T,
                deferRender = T,
                scrollCollapse = T,
                callback = JS("$.fn.dataTable.ext.errMode = 'none';")
              ))

```
